### PR TITLE
Update README with type documentation.

### PR DESCRIPTION
**Pull request by Ziaunys**
- Adds basic documentation for the Class parameters and various types
  that the module provides.

### CODE REVIEW

**Comment by kfjohnson** [comment]
+1

**Comment by discreet** [comment]
@Ziaunys since you added the documentation i was curious if there is a way to have multiple settings/values for the same section when using the forwarder_input and forwarder_output types.

**Comment by Ziaunys** [comment]
@discreet You could pass multiple forwarder inputs and outputs to the forwarder_input and forwarder_output parameters since it's just taking those hashes and calling create resources on them. I can update the docs to make that more clear.

**Comment by discreet** [comment]
@Ziaunys that would be awesome. To clarify though in the params.pp we see this as the default to forwarder_output:

 $forwarder_output = {
    "tcpout_defaultgroup"          => {
      section                      => 'default',
      setting                      => 'defaultGroup',
      value                        => "${server}_${logging_port}",
      tag                          => 'splunk_forwarder'
    },

I'm looking to achieve an output.conf like below (*ip addresses removed):

[default]
defaultGroup = SplunkCluster
disabled = false
[tcpout:SplunkClusterProd]
server = $IPone:$port, $IPtwo:$port
useACK = true
maxQueueSize = 7MB

**Pull request merged**
